//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// FlexberryAdvLimit.
    /// </summary>
    // *** Start programmer edit section *** (FlexberryAdvLimit CustomAttributes)

    // *** End programmer edit section *** (FlexberryAdvLimit CustomAttributes)
    [PublishName("FlexberryAdvLimit")]
    [ClassStorage("STORMAdvLimit")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("FlexberryAdvLimitE", new string[] {
            "User",
            "Published",
            "Module",
            "Name",
            "Value"})]
    [View("FlexberryAdvLimitL", new string[] {
            "User",
            "Published",
            "Module",
            "Name"})]
    public class FlexberryAdvLimit : ICSSoft.STORMNET.DataObject
    {

        private string fUser;

        private bool fPublished;

        private string fModule;

        private string fName;

        private string fValue;

        // *** Start programmer edit section *** (FlexberryAdvLimit CustomMembers)

        // *** End programmer edit section *** (FlexberryAdvLimit CustomMembers)


        /// <summary>
        /// User.
        /// </summary>
        // *** Start programmer edit section *** (FlexberryAdvLimit.User CustomAttributes)

        // *** End programmer edit section *** (FlexberryAdvLimit.User CustomAttributes)
        [StrLen(256)]
        public virtual string User
        {
            get
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.User Get start)

                // *** End programmer edit section *** (FlexberryAdvLimit.User Get start)
                string result = this.fUser;
                // *** Start programmer edit section *** (FlexberryAdvLimit.User Get end)

                // *** End programmer edit section *** (FlexberryAdvLimit.User Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.User Set start)

                // *** End programmer edit section *** (FlexberryAdvLimit.User Set start)
                this.fUser = value;
                // *** Start programmer edit section *** (FlexberryAdvLimit.User Set end)

                // *** End programmer edit section *** (FlexberryAdvLimit.User Set end)
            }
        }

        /// <summary>
        /// Published.
        /// </summary>
        // *** Start programmer edit section *** (FlexberryAdvLimit.Published CustomAttributes)

        // *** End programmer edit section *** (FlexberryAdvLimit.Published CustomAttributes)
        public virtual bool Published
        {
            get
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Published Get start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Published Get start)
                bool result = this.fPublished;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Published Get end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Published Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Published Set start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Published Set start)
                this.fPublished = value;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Published Set end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Published Set end)
            }
        }

        /// <summary>
        /// Module.
        /// </summary>
        // *** Start programmer edit section *** (FlexberryAdvLimit.Module CustomAttributes)

        // *** End programmer edit section *** (FlexberryAdvLimit.Module CustomAttributes)
        [StrLen(256)]
        public virtual string Module
        {
            get
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Module Get start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Module Get start)
                string result = this.fModule;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Module Get end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Module Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Module Set start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Module Set start)
                this.fModule = value;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Module Set end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Module Set end)
            }
        }

        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (FlexberryAdvLimit.Name CustomAttributes)

        // *** End programmer edit section *** (FlexberryAdvLimit.Name CustomAttributes)
        [StrLen(256)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Name Get start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Name Get end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Name Set start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Name Set end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Name Set end)
            }
        }

        /// <summary>
        /// Value.
        /// </summary>
        // *** Start programmer edit section *** (FlexberryAdvLimit.Value CustomAttributes)

        // *** End programmer edit section *** (FlexberryAdvLimit.Value CustomAttributes)
        public virtual string Value
        {
            get
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Value Get start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Value Get start)
                string result = this.fValue;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Value Get end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Value Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (FlexberryAdvLimit.Value Set start)

                // *** End programmer edit section *** (FlexberryAdvLimit.Value Set start)
                this.fValue = value;
                // *** Start programmer edit section *** (FlexberryAdvLimit.Value Set end)

                // *** End programmer edit section *** (FlexberryAdvLimit.Value Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "FlexberryAdvLimitE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FlexberryAdvLimitE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FlexberryAdvLimitE", typeof(NewPlatform.Flexberry.FlexberryAdvLimit));
                }
            }

            /// <summary>
            /// "FlexberryAdvLimitL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FlexberryAdvLimitL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FlexberryAdvLimitL", typeof(NewPlatform.Flexberry.FlexberryAdvLimit));
                }
            }
        }
    }
}
