//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSSoft.Services
{
    using System;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (UserSetting CustomAttributes)

    // *** End programmer edit section *** (UserSetting CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("all", new string[] {
            "AppName",
            "UserName",
            "UserGuid",
            "ModuleName",
            "ModuleGuid",
            "SettName",
            "SettGuid",
            "StrVal",
            "TxtVal",
            "IntVal",
            "BoolVal",
            "GuidVal",
            "SettLastAccessTime",
            "DecimalVal",
            "DateTimeVal"})]
    public class UserSetting : ICSSoft.STORMNET.DataObject
    {
        
        private string fAppName;
        
        private string fUserName;
        
        private System.Nullable<Guid> fUserGuid;
        
        private string fModuleName;
        
        private System.Nullable<Guid> fModuleGuid;
        
        private string fSettName;
        
        private System.Nullable<Guid> fSettGuid;
        
        private System.DateTime fSettLastAccessTime = System.DateTime.Now;
        
        private string fStrVal;
        
        private string fTxtVal;
        
        private System.Nullable<int> fIntVal;
        
        private System.Nullable<bool> fBoolVal;
        
        private System.Nullable<Guid> fGuidVal;
        
        private System.Nullable<decimal> fDecimalVal;
        
        private System.Nullable<DateTime> fDateTimeVal;
        
        // *** Start programmer edit section *** (UserSetting CustomMembers)

        // *** End programmer edit section *** (UserSetting CustomMembers)

        
        // *** Start programmer edit section *** (UserSetting.AppName CustomAttributes)
        // *** End programmer edit section *** (UserSetting.AppName CustomAttributes)
        [StrLen(256)]
        public virtual string AppName
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.AppName Get start)
                // *** End programmer edit section *** (UserSetting.AppName Get start)
                string result = this.fAppName;
                // *** Start programmer edit section *** (UserSetting.AppName Get end)
                // *** End programmer edit section *** (UserSetting.AppName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.AppName Set start)
                // *** End programmer edit section *** (UserSetting.AppName Set start)
                this.fAppName = value;
                // *** Start programmer edit section *** (UserSetting.AppName Set end)
                // *** End programmer edit section *** (UserSetting.AppName Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.UserName CustomAttributes)

        // *** End programmer edit section *** (UserSetting.UserName CustomAttributes)
        [StrLen(512)]
        public virtual string UserName
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.UserName Get start)

                // *** End programmer edit section *** (UserSetting.UserName Get start)
                string result = this.fUserName;
                // *** Start programmer edit section *** (UserSetting.UserName Get end)

                // *** End programmer edit section *** (UserSetting.UserName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.UserName Set start)

                // *** End programmer edit section *** (UserSetting.UserName Set start)
                this.fUserName = value;
                // *** Start programmer edit section *** (UserSetting.UserName Set end)

                // *** End programmer edit section *** (UserSetting.UserName Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.UserGuid CustomAttributes)

        // *** End programmer edit section *** (UserSetting.UserGuid CustomAttributes)
        public virtual System.Nullable<Guid> UserGuid
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.UserGuid Get start)

                // *** End programmer edit section *** (UserSetting.UserGuid Get start)
                System.Nullable<Guid> result = this.fUserGuid;
                // *** Start programmer edit section *** (UserSetting.UserGuid Get end)

                // *** End programmer edit section *** (UserSetting.UserGuid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.UserGuid Set start)

                // *** End programmer edit section *** (UserSetting.UserGuid Set start)
                this.fUserGuid = value;
                // *** Start programmer edit section *** (UserSetting.UserGuid Set end)

                // *** End programmer edit section *** (UserSetting.UserGuid Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.ModuleName CustomAttributes)
        // *** End programmer edit section *** (UserSetting.ModuleName CustomAttributes)
        [StrLen(1024)]
        public virtual string ModuleName
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.ModuleName Get start)
                // *** End programmer edit section *** (UserSetting.ModuleName Get start)
                string result = this.fModuleName;
                // *** Start programmer edit section *** (UserSetting.ModuleName Get end)
                // *** End programmer edit section *** (UserSetting.ModuleName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.ModuleName Set start)
                // *** End programmer edit section *** (UserSetting.ModuleName Set start)
                this.fModuleName = value;
                // *** Start programmer edit section *** (UserSetting.ModuleName Set end)
                // *** End programmer edit section *** (UserSetting.ModuleName Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.ModuleGuid CustomAttributes)

        // *** End programmer edit section *** (UserSetting.ModuleGuid CustomAttributes)
        public virtual System.Nullable<Guid> ModuleGuid
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.ModuleGuid Get start)

                // *** End programmer edit section *** (UserSetting.ModuleGuid Get start)
                System.Nullable<Guid> result = this.fModuleGuid;
                // *** Start programmer edit section *** (UserSetting.ModuleGuid Get end)

                // *** End programmer edit section *** (UserSetting.ModuleGuid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.ModuleGuid Set start)

                // *** End programmer edit section *** (UserSetting.ModuleGuid Set start)
                this.fModuleGuid = value;
                // *** Start programmer edit section *** (UserSetting.ModuleGuid Set end)

                // *** End programmer edit section *** (UserSetting.ModuleGuid Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.SettName CustomAttributes)

        // *** End programmer edit section *** (UserSetting.SettName CustomAttributes)
        [StrLen(256)]
        public virtual string SettName
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.SettName Get start)

                // *** End programmer edit section *** (UserSetting.SettName Get start)
                string result = this.fSettName;
                // *** Start programmer edit section *** (UserSetting.SettName Get end)

                // *** End programmer edit section *** (UserSetting.SettName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.SettName Set start)

                // *** End programmer edit section *** (UserSetting.SettName Set start)
                this.fSettName = value;
                // *** Start programmer edit section *** (UserSetting.SettName Set end)

                // *** End programmer edit section *** (UserSetting.SettName Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.SettGuid CustomAttributes)

        // *** End programmer edit section *** (UserSetting.SettGuid CustomAttributes)
        public virtual System.Nullable<Guid> SettGuid
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.SettGuid Get start)

                // *** End programmer edit section *** (UserSetting.SettGuid Get start)
                System.Nullable<Guid> result = this.fSettGuid;
                // *** Start programmer edit section *** (UserSetting.SettGuid Get end)

                // *** End programmer edit section *** (UserSetting.SettGuid Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.SettGuid Set start)

                // *** End programmer edit section *** (UserSetting.SettGuid Set start)
                this.fSettGuid = value;
                // *** Start programmer edit section *** (UserSetting.SettGuid Set end)

                // *** End programmer edit section *** (UserSetting.SettGuid Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.SettLastAccessTime CustomAttributes)

        // *** End programmer edit section *** (UserSetting.SettLastAccessTime CustomAttributes)
        public virtual System.DateTime SettLastAccessTime
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.SettLastAccessTime Get start)

                // *** End programmer edit section *** (UserSetting.SettLastAccessTime Get start)
                System.DateTime result = this.fSettLastAccessTime;
                // *** Start programmer edit section *** (UserSetting.SettLastAccessTime Get end)

                // *** End programmer edit section *** (UserSetting.SettLastAccessTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.SettLastAccessTime Set start)

                // *** End programmer edit section *** (UserSetting.SettLastAccessTime Set start)
                this.fSettLastAccessTime = value;
                // *** Start programmer edit section *** (UserSetting.SettLastAccessTime Set end)

                // *** End programmer edit section *** (UserSetting.SettLastAccessTime Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.StrVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.StrVal CustomAttributes)
        [StrLen(256)]
        public virtual string StrVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.StrVal Get start)

                // *** End programmer edit section *** (UserSetting.StrVal Get start)
                string result = this.fStrVal;
                // *** Start programmer edit section *** (UserSetting.StrVal Get end)

                // *** End programmer edit section *** (UserSetting.StrVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.StrVal Set start)

                // *** End programmer edit section *** (UserSetting.StrVal Set start)
                this.fStrVal = value;
                // *** Start programmer edit section *** (UserSetting.StrVal Set end)

                // *** End programmer edit section *** (UserSetting.StrVal Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.TxtVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.TxtVal CustomAttributes)
        public virtual string TxtVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.TxtVal Get start)

                // *** End programmer edit section *** (UserSetting.TxtVal Get start)
                string result = this.fTxtVal;
                // *** Start programmer edit section *** (UserSetting.TxtVal Get end)

                // *** End programmer edit section *** (UserSetting.TxtVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.TxtVal Set start)

                // *** End programmer edit section *** (UserSetting.TxtVal Set start)
                this.fTxtVal = value;
                // *** Start programmer edit section *** (UserSetting.TxtVal Set end)

                // *** End programmer edit section *** (UserSetting.TxtVal Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.IntVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.IntVal CustomAttributes)
        public virtual System.Nullable<int> IntVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.IntVal Get start)

                // *** End programmer edit section *** (UserSetting.IntVal Get start)
                System.Nullable<int> result = this.fIntVal;
                // *** Start programmer edit section *** (UserSetting.IntVal Get end)

                // *** End programmer edit section *** (UserSetting.IntVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.IntVal Set start)

                // *** End programmer edit section *** (UserSetting.IntVal Set start)
                this.fIntVal = value;
                // *** Start programmer edit section *** (UserSetting.IntVal Set end)

                // *** End programmer edit section *** (UserSetting.IntVal Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.BoolVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.BoolVal CustomAttributes)
        public virtual System.Nullable<bool> BoolVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.BoolVal Get start)

                // *** End programmer edit section *** (UserSetting.BoolVal Get start)
                System.Nullable<bool> result = this.fBoolVal;
                // *** Start programmer edit section *** (UserSetting.BoolVal Get end)

                // *** End programmer edit section *** (UserSetting.BoolVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.BoolVal Set start)

                // *** End programmer edit section *** (UserSetting.BoolVal Set start)
                this.fBoolVal = value;
                // *** Start programmer edit section *** (UserSetting.BoolVal Set end)

                // *** End programmer edit section *** (UserSetting.BoolVal Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.GuidVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.GuidVal CustomAttributes)
        public virtual System.Nullable<Guid> GuidVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.GuidVal Get start)

                // *** End programmer edit section *** (UserSetting.GuidVal Get start)
                System.Nullable<Guid> result = this.fGuidVal;
                // *** Start programmer edit section *** (UserSetting.GuidVal Get end)

                // *** End programmer edit section *** (UserSetting.GuidVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.GuidVal Set start)

                // *** End programmer edit section *** (UserSetting.GuidVal Set start)
                this.fGuidVal = value;
                // *** Start programmer edit section *** (UserSetting.GuidVal Set end)

                // *** End programmer edit section *** (UserSetting.GuidVal Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.DecimalVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.DecimalVal CustomAttributes)
        public virtual System.Nullable<decimal> DecimalVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.DecimalVal Get start)

                // *** End programmer edit section *** (UserSetting.DecimalVal Get start)
                System.Nullable<decimal> result = this.fDecimalVal;
                // *** Start programmer edit section *** (UserSetting.DecimalVal Get end)

                // *** End programmer edit section *** (UserSetting.DecimalVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.DecimalVal Set start)

                // *** End programmer edit section *** (UserSetting.DecimalVal Set start)
                this.fDecimalVal = value;
                // *** Start programmer edit section *** (UserSetting.DecimalVal Set end)

                // *** End programmer edit section *** (UserSetting.DecimalVal Set end)
            }
        }
        
        // *** Start programmer edit section *** (UserSetting.DateTimeVal CustomAttributes)

        // *** End programmer edit section *** (UserSetting.DateTimeVal CustomAttributes)
        public virtual System.Nullable<DateTime> DateTimeVal
        {
            get
            {
                // *** Start programmer edit section *** (UserSetting.DateTimeVal Get start)

                // *** End programmer edit section *** (UserSetting.DateTimeVal Get start)
                System.Nullable<DateTime> result = this.fDateTimeVal;
                // *** Start programmer edit section *** (UserSetting.DateTimeVal Get end)

                // *** End programmer edit section *** (UserSetting.DateTimeVal Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (UserSetting.DateTimeVal Set start)

                // *** End programmer edit section *** (UserSetting.DateTimeVal Set start)
                this.fDateTimeVal = value;
                // *** Start programmer edit section *** (UserSetting.DateTimeVal Set end)

                // *** End programmer edit section *** (UserSetting.DateTimeVal Set end)
            }
        }
    }
}
